config/routes.rb
Rails.application.routes.draw do
  resources :songs, path: '/'

end

app/models/song.rb
class Song < ActiveRecord::Base
  def youtube_test
    true
  end
  
  def youtube_url
    if youtube_id
      if youtube_start_time && youtube_start_time > 0
        "https://www.youtube.com/watch?v=#{youtube_id}&t=#{youtube_start_time}"
      else
        "https://www.youtube.com/watch?v=#{youtube_id}"
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :artist, :word, :lyrics, :used, :winner, :youtube_id, :youtube_start_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/_footer.html.erb
<p>Version: <%= APP_VERSION %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ytunes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.indigo-pink.min.css">
  <script src="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.min.js"></script>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :lyrics %><br>
    <%= f.text_area :lyrics %>
  </div>
  <div class="field">
    <%= f.label :used %><br>
    <%= f.check_box :used %>
  </div>
  <div class="field">
    <%= f.label :winner %><br>
    <%= f.text_field :winner %>
  </div>
  <div class="field">
    <%= f.label :youtube_id %><br>
    <%= f.text_field :youtube_id %>
  </div>
  <div class="field">
    <%= f.label :youtube_start_time %><br>
    <%= f.number_field :youtube_start_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Songs</h1>

<table class="mdl-data-table mdl-js-data-table">
  <thead>
    <tr>
      <th class="mdl-data-table__cell--non-numeric">Title</th>
      <th class="mdl-data-table__cell--non-numeric">Artist</th>
      <th class="mdl-data-table__cell--non-numeric">Word</th>
      <th class="mdl-data-table__cell--non-numeric">Lyrics</th>
      <th>Used</th>
      <th>Winner</th>
      <th>Youtube</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr data-link="<%= song.youtube_url %>">
        <td class="mdl-data-table__cell--non-numeric mdl-data-table--selectable"><%= song.title %></td>
        <td class="mdl-data-table__cell--non-numeric"><%= song.artist %></td>
        <td class="mdl-data-table__cell--non-numeric"><%= song.word %></td>
        <td class="mdl-data-table__cell--non-numeric"><%= highlight(simple_format(excerpt(song.lyrics, song.word, radius: 75)), song.word) %></td>
        <td><%= song.used ? 'Yes' : '' %></td>
        <td><%= song.winner ? song.winner : '' %></td>
        <td><%= link_to(song.youtube_id, song.youtube_url, target: "_blank") %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= link_to 'Edit', edit_song_path(@song) %> |
  <%= link_to 'Back', songs_path %>
</p>

<section>
  <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @song.youtube_id %>?start=<%= @song.youtube_start_time %>" frameborder="0" allowfullscreen></iframe>
</section>

<section>
  <h2><%= @song.title %></h2>
  <h3><%= @song.artist %></h3>
</section>

<p>
  <strong>Keyword:</strong>
  <span class="keyword"><%= @song.word %></span>
</p>

<p>
  <%= highlight(simple_format(@song.lyrics), @song.word) %>
</p>

<p>
  <strong>Used:</strong>
  <%= @song.used %>
</p>

<p>
  <strong>Winner:</strong>
  <%= @song.winner %>
</p>